//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveReports.Samples.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActiveReports.Samples.Designer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デザイナについて(&amp;A)....
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdExport {
            get {
                object obj = ResourceManager.GetObject("CmdExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdNewReport {
            get {
                object obj = ResourceManager.GetObject("CmdNewReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdOpen {
            get {
                object obj = ResourceManager.GetObject("CmdOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdSave {
            get {
                object obj = ResourceManager.GetObject("CmdSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdSaveAs {
            get {
                object obj = ResourceManager.GetObject("CmdSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在の選択: .
        /// </summary>
        internal static string CurrentSelection {
            get {
                return ResourceManager.GetString("CurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports.
        /// </summary>
        internal static string DefaultGroup {
            get {
                return ResourceManager.GetString("DefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規ページレポート.rdlx.
        /// </summary>
        internal static string DefaultReportNamePage {
            get {
                return ResourceManager.GetString("DefaultReportNamePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規RDLレポート.rdlx.
        /// </summary>
        internal static string DefaultReportNameRdl {
            get {
                return ResourceManager.GetString("DefaultReportNameRdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規ダッシュボード.rdlx.
        /// </summary>
        internal static string DefaultReportNameRdlDashboard {
            get {
                return ResourceManager.GetString("DefaultReportNameRdlDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規RDLレポート.rdlx.
        /// </summary>
        internal static string DefaultReportNameRdlx {
            get {
                return ResourceManager.GetString("DefaultReportNameRdlx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規マスターレポート.rdlx-master.
        /// </summary>
        internal static string DefaultReportNameRdlxMaster {
            get {
                return ResourceManager.GetString("DefaultReportNameRdlxMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規セクションレポート.rpx.
        /// </summary>
        internal static string DefaultReportNameRpx {
            get {
                return ResourceManager.GetString("DefaultReportNameRpx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignerForm.
        /// </summary>
        internal static string DesignerFormName {
            get {
                return ResourceManager.GetString("DesignerFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エンドユーザーデザイナ.
        /// </summary>
        internal static string DesignerFormTitle {
            get {
                return ResourceManager.GetString("DesignerFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string DirtySign {
            get {
                return ResourceManager.GetString("DirtySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} への変更を保存しますか？.
        /// </summary>
        internal static string EudUnsavedChangesMessage {
            get {
                return ResourceManager.GetString("EudUnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未保存の変更.
        /// </summary>
        internal static string EudUnsavedChangesTitle {
            get {
                return ResourceManager.GetString("EudUnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エクスポート(&amp;E)....
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupEditorHide {
            get {
                object obj = ResourceManager.GetObject("GroupEditorHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupEditorShow {
            get {
                object obj = ResourceManager.GetObject("GroupEditorShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ(&amp;H).
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グループエディタの非表示.
        /// </summary>
        internal static string HideGroupPanelToolTip {
            get {
                return ResourceManager.GetString("HideGroupPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成(&amp;N)....
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        internal static string NewToolTip {
            get {
                return ResourceManager.GetString("NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されていません.
        /// </summary>
        internal static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開く(&amp;O)....
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ライブラリとして開く.
        /// </summary>
        internal static string OpenAsLibrary {
            get {
                return ResourceManager.GetString("OpenAsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開く.
        /// </summary>
        internal static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rdl.
        /// </summary>
        internal static string RdlExtension {
            get {
                return ResourceManager.GetString("RdlExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rdlx.
        /// </summary>
        internal static string RdlxExtension {
            get {
                return ResourceManager.GetString("RdlxExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rdlx-master.
        /// </summary>
        internal static string RdlxMasterExtension {
            get {
                return ResourceManager.GetString("RdlxMasterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル {0} は有効なレポートファイルではありません。.
        /// </summary>
        internal static string ReportIsNotValid {
            get {
                return ResourceManager.GetString("ReportIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rpx.
        /// </summary>
        internal static string RpxExtension {
            get {
                return ResourceManager.GetString("RpxExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上書き保存(&amp;S).
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前を付けて保存(&amp;A)....
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDLレポートファイル (*.rdlx)|*.rdlx.
        /// </summary>
        internal static string SaveRdlFilter {
            get {
                return ResourceManager.GetString("SaveRdlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページレポートファイル (*.rdlx)|*.rdlx.
        /// </summary>
        internal static string SaveRdlxFilter {
            get {
                return ResourceManager.GetString("SaveRdlxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDLレポートマスターファイル (*.rdlx-master)|*.rdlx-master.
        /// </summary>
        internal static string SaveRdlxMasterFilter {
            get {
                return ResourceManager.GetString("SaveRdlxMasterFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rpxファイル|*.rpx.
        /// </summary>
        internal static string SaveRpxFilter {
            get {
                return ResourceManager.GetString("SaveRpxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上書き保存.
        /// </summary>
        internal static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グループエディタの表示.
        /// </summary>
        internal static string ShowGroupPanelToolTip {
            get {
                return ResourceManager.GetString("ShowGroupPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} - {2}.
        /// </summary>
        internal static string TitleFormat {
            get {
                return ResourceManager.GetString("TitleFormat", resourceCulture);
            }
        }
    }
}
