'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ActiveReports.Samples.WebService.Resource", GetType(Resource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JsonDataSource サンプルのWebサービスが正しく開始されました。.
        '''</summary>
        Friend Shared ReadOnly Property bodyOfMessage() As String
            Get
                Return ResourceManager.GetString("bodyOfMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;Customers&quot;:[{&quot;CustomerID&quot;:&quot;1&quot;,&quot;CompanyName&quot;:&quot;喫茶たいむましん&quot;,&quot;ContactName&quot;:&quot;林　 千春&quot;,&quot;ContactTitle&quot;:&quot;店長&quot;,&quot;Address&quot;:&quot;佐賀市長瀬町 23-XX&quot;,&quot;City&quot;:&quot;佐賀市&quot;,&quot;Region&quot;:&quot;&quot;,&quot;PostalCode&quot;:&quot;840-0853&quot;,&quot;Country&quot;:&quot;佐賀県&quot;,&quot;Phone&quot;:&quot;(0952)26-64XX&quot;,&quot;Fax&quot;:&quot;&quot;},{&quot;CustomerID&quot;:&quot;10&quot;,&quot;CompanyName&quot;:&quot;東海道スーパー&quot;,&quot;ContactName&quot;:&quot;河本 なみ&quot;,&quot;ContactTitle&quot;:&quot;料理長&quot;,&quot;Address&quot;:&quot;那覇市繁多川 1-21-XX&quot;,&quot;City&quot;:&quot;那覇市&quot;,&quot;Region&quot;:&quot;&quot;,&quot;PostalCode&quot;:&quot;902-0071&quot;,&quot;Country&quot;:&quot;沖縄県&quot;,&quot;Phone&quot;:&quot;(0988)55-87XX&quot;,&quot;Fax&quot;:&quot;(0988)55-87XX&quot;},{&quot;CustomerID&quot;:&quot;11&quot;,&quot;CompanyName&quot;:&quot;小町ストアー&quot;,&quot;ContactName&quot;:&quot;山久 良美&quot;....
        '''</summary>
        Friend Shared ReadOnly Property customers() As String
            Get
                Return ResourceManager.GetString("customers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to メッセージ: {0}, StackTrace: {1}.
        '''</summary>
        Friend Shared ReadOnly Property FormatErrorMessage() As String
            Get
                Return ResourceManager.GetString("FormatErrorMessage", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
