'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ActiveReports.Samples.Designer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to デザイナについて(&amp;A)....
        '''</summary>
        Friend Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property App() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("App", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property CmdExport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdExport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property CmdNewReport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdNewReport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property CmdOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property CmdSave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdSave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property CmdSaveAs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CmdSaveAs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 現在の選択: .
        '''</summary>
        Friend Shared ReadOnly Property CurrentSelection() As String
            Get
                Return ResourceManager.GetString("CurrentSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ActiveReports.
        '''</summary>
        Friend Shared ReadOnly Property DefaultGroup() As String
            Get
                Return ResourceManager.GetString("DefaultGroup", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 新規ページレポート.rdlx.
        '''</summary>
        Friend Shared ReadOnly Property DefaultReportNamePage() As String
            Get
                Return ResourceManager.GetString("DefaultReportNamePage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 新規RDLレポート.rdlx.
        '''</summary>
        Friend Shared ReadOnly Property DefaultReportNameRdl() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRdl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新規ページレポート.rdlx.
        '''</summary>
        Friend Shared ReadOnly Property DefaultReportNameRdlx() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRdlx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新規マスターレポート.rdlx-master.
        '''</summary>
        Friend Shared ReadOnly Property DefaultReportNameRdlxMaster() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRdlxMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新規セクションレポート.rpx.
        '''</summary>
        Friend Shared ReadOnly Property DefaultReportNameRpx() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRpx", resourceCulture)
            End Get
        End Property
		
		'''<summary>
        '''  Looks up a localized string similar to 新規ダッシュボード.rdlx.
        '''</summary>
        Friend Shared ReadOnly Property DefaultReportNameRdlDashboard() As String
            Get
                Return ResourceManager.GetString("DefaultReportNameRdlDashboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DesignerForm.
        '''</summary>
        Friend Shared ReadOnly Property DesignerFormName() As String
            Get
                Return ResourceManager.GetString("DesignerFormName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *.
        '''</summary>
        Friend Shared ReadOnly Property DirtySign() As String
            Get
                Return ResourceManager.GetString("DirtySign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} への変更を保存しますか？.
        '''</summary>
        Friend Shared ReadOnly Property EudUnsavedChangesMessage() As String
            Get
                Return ResourceManager.GetString("EudUnsavedChangesMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未保存の変更.
        '''</summary>
        Friend Shared ReadOnly Property EudUnsavedChangesTitle() As String
            Get
                Return ResourceManager.GetString("EudUnsavedChangesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 終了.
        '''</summary>
        Friend Shared ReadOnly Property ExitText() As String
            Get
                Return ResourceManager.GetString("ExitText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to エクスポート(&amp;E)....
        '''</summary>
        Friend Shared ReadOnly Property Export() As String
            Get
                Return ResourceManager.GetString("Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property GroupEditorHide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupEditorHide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property GroupEditorShow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupEditorShow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ヘルプ(&amp;H).
        '''</summary>
        Friend Shared ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to グループエディタの非表示.
        '''</summary>
        Friend Shared ReadOnly Property HideGroupPanelToolTip() As String
            Get
                Return ResourceManager.GetString("HideGroupPanelToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新規作成(&amp;N)....
        '''</summary>
        Friend Shared ReadOnly Property NewText() As String
            Get
                Return ResourceManager.GetString("NewText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新規作成.
        '''</summary>
        Friend Shared ReadOnly Property NewToolTip() As String
            Get
                Return ResourceManager.GetString("NewToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 選択されていません.
        '''</summary>
        Friend Shared ReadOnly Property NoSelection() As String
            Get
                Return ResourceManager.GetString("NoSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 開く(&amp;O)....
        '''</summary>
        Friend Shared ReadOnly Property Open() As String
            Get
                Return ResourceManager.GetString("Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ライブラリとして開く.
        '''</summary>
        Friend Shared ReadOnly Property OpenAsLibrary() As String
            Get
                Return ResourceManager.GetString("OpenAsLibrary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 開く.
        '''</summary>
        Friend Shared ReadOnly Property OpenToolTip() As String
            Get
                Return ResourceManager.GetString("OpenToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .rdl.
        '''</summary>
        Friend Shared ReadOnly Property RdlExtension() As String
            Get
                Return ResourceManager.GetString("RdlExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .rdlx.
        '''</summary>
        Friend Shared ReadOnly Property RdlxExtension() As String
            Get
                Return ResourceManager.GetString("RdlxExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .rdlx-master.
        '''</summary>
        Friend Shared ReadOnly Property RdlxMasterExtension() As String
            Get
                Return ResourceManager.GetString("RdlxMasterExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ファイル {0} は有効なレポートファイルではありません。.
        '''</summary>
        Friend Shared ReadOnly Property ReportIsNotValid() As String
            Get
                Return ResourceManager.GetString("ReportIsNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .rpx.
        '''</summary>
        Friend Shared ReadOnly Property RpxExtension() As String
            Get
                Return ResourceManager.GetString("RpxExtension", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to エンドユーザーデザイナ.
        '''</summary>
        Friend Shared ReadOnly Property DesignerFormTitle() As String
            Get
                Return ResourceManager.GetString("DesignerFormTitle", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 上書き保存(&amp;S).
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 名前を付けて保存(&amp;A)....
        '''</summary>
        Friend Shared ReadOnly Property SaveAs() As String
            Get
                Return ResourceManager.GetString("SaveAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RDLレポートファイル (*.rdlx)|*.rdlx.
        '''</summary>
        Friend Shared ReadOnly Property SaveRdlFilter() As String
            Get
                Return ResourceManager.GetString("SaveRdlFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ページレポートファイル (*.rdlx)|*.rdlx.
        '''</summary>
        Friend Shared ReadOnly Property SaveRdlxFilter() As String
            Get
                Return ResourceManager.GetString("SaveRdlxFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RDLレポートマスターファイル (*.rdlx-master)|*.rdlx-master.
        '''</summary>
        Friend Shared ReadOnly Property SaveRdlxMasterFilter() As String
            Get
                Return ResourceManager.GetString("SaveRdlxMasterFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rpxファイル|*.rpx.
        '''</summary>
        Friend Shared ReadOnly Property SaveRpxFilter() As String
            Get
                Return ResourceManager.GetString("SaveRpxFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 上書き保存.
        '''</summary>
        Friend Shared ReadOnly Property SaveToolTip() As String
            Get
                Return ResourceManager.GetString("SaveToolTip", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to グループエディタの表示.
        '''</summary>
        Friend Shared ReadOnly Property ShowGroupPanelToolTip() As String
            Get
                Return ResourceManager.GetString("ShowGroupPanelToolTip", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {0}{1} - {2}.
        '''</summary>
        Friend Shared ReadOnly Property TitleFormat() As String
            Get
                Return ResourceManager.GetString("TitleFormat", resourceCulture)
            End Get
        End Property

    End Class
End Namespace
